
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_development

test:
  <<: *default
  database: twitter_test

production:
  adapter: pg
  database: db/production.pg
