# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b998ad963382321dc2c390af8ba11ac9ba24ddb462dc0abde45b4129954f54190fa6d000635eefd165c23118f370d1167798875b9cda5439bd86f5fcac656d5d

test:
  secret_key_base: a71c3cdf64526b083d8de89d4421b9b0f07fb4852bc8d0ccb63983582e290d5f6db0df53846d2dc7ebb795527733208410256fed70ac6cf3a35db0d9a6d4224a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
